kind: Service
apiVersion: v1
metadata:
  name: projectservice-svc
spec:
  selector:
    app: projectservice
  ports:
  - protocol: TCP
    port: 9095
    nodePort: 30082
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice-deployment
spec:
  selector:
      matchLabels:
        app: projectservice
  replicas: 1
  template:
    metadata:
      labels:
        app: projectservice
    spec:
      containers:
        - name: projectservice
          image: projectservice:4.0
          imagePullPolicy: Never
          ports:
          - containerPort: 9095
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  
