apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice-deployment
  labels:
    app: projectservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projectservice
  template:
    metadata:
      labels:
        app: projectservice
    spec:
      containers:
      - name: projectservice
        image: projectservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9095
