spring:
  application:
    name: eurekaservice
server:
  port: 8761
eureka:
  instance:
  hostname: "${HOSTNAME}.eureka"
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
