apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviqdb
  name: deviqdb-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: deviqdb
  clusterIP: None

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviqdb
  labels:
    app: deviqdb
spec:
  selector:
    matchLabels:
      app: deviqdb
  replicas: 1
  template:
    metadata:
      labels:
        app: deviqdb
      name: deviqdb-service

    spec:
      containers:
        - image: mongo:latest
          name: deviqdb
          ports:
            - containerPort: 27017
              name: deviqdb