apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: "eureka"
  replicas: 1
  selector:
    matchLabels:
      app: eureka
      env: green
  template:
    metadata:
      labels:
        app: eureka
        env: green
    spec:
      containers:
        - name: eureka
          image: eurekaservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address