apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice-deployment
  labels:
    app: gatewayservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayservice
  template:
    metadata:
      labels:
        app: gatewayservice
    spec:
      containers:
      - name: gatewayservice
        image: gatewayservice:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 9091

---

kind: Service
apiVersion: v1
metadata:
  name: gatewayservice-svc
spec:
  selector:
    app: gatewayservice
  ports:
    - protocol: TCP
      port: 9091
      nodePort: 30083
  type: NodePort