apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice-deployment
  labels:
    app: projectservice
spec:
  selector:
    matchLabels:
      app: projectservice
      env: blue
  replicas: 2
  template:
    metadata:
      labels:
        app: projectservice
        env: blue
    spec:
      containers:
        - name: projectservice
          image: janakapushpakumara/projectservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9095
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: host