apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
  labels:
    app: authservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authservice
      env: blue
  template:
    metadata:
      labels:
        app: authservice
        env: blue
    spec:
      containers:
        - name: authservice
          image: janakapushpakumara/authservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
          env:
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf
                  key: host
