spring:
  application:
    name: auth-service
server:
  port: 9092
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  instance:
    preferIpAddress: true