spring:
  application:
    name: auth-service
server:
  port: 9095
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    preferIpAddress: true