kind: Service
apiVersion: v1
metadata:
  name: gatewayservice-svc
spec:
  selector:
    app: gatewayservice
    env: blue
  ports:
    - protocol: TCP
      port: 9091
      nodePort: 30083
  type: NodePort