apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayservice-deployment
  labels:
    app: gatewayservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatewayservice
      env: green
  template:
    metadata:
      labels:
        app: gatewayservice
        env: green
    spec:
      containers:
        - name: gatewayservice
          image: janakapushpakumara/gatewayservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9091
