spring:
  application:
    name: project-service

server:
  port: 9095

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}
  instance:
    preferIpAddress: true
  data:
    mongodb:
      host: '${MONGO_HOST}'
      port: 27017
      database: '${MONGO_DB}'