spring:
  application:
    name: project-service
server:
  port: 8085
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka}
  instance:
    preferIpAddress: true