server:
  port: 9091
debug: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

spring:
  application:
    name: apigatewayservice
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - StripPrefix=2
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            backoff:
              firstBackoff: 50ms
              maxBackoff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: projectservice
          uri: lb://projectservice
          predicates:
            - Path=/gateway/projectservice/**
          filters:
            - AuthenticationFilter

        - id: authservice
          uri: lb://authservice
          predicates:
            - Path=/gateway/authservice/**
          filters:
            - AuthenticationFilter

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/gateway/userservice/**
          filters:
            - AuthenticationFilter
